# Default values for register-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: Always

config:
  connect:
  token: ""
  tillerConnectionTimeout: 2
  port: 8088
  logLevel: 0
  envId: ""
  sshIdentity: ""
  git:
    url: ""
  extraArgs:

logs:
  parser: docker

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 512Mi
  requests:
    # cpu: 100m
    memory: 256Mi

rbac:
  create: false
  serviceAccountName: default